apiVersion: v1
kind: Secret

metadata:
  name: backend-secret
  namespace: mapub

type: Opaque

stringData:
  DB_USER: "postgresadmin"
  DB_PASSWORD: "SenhaForte@2026!"

  JWT_SECRET: "seu_jwt_secret_super_secreto_para_desenvolvimento_123456"